- name: variables and PLAY level
  hosts: localhost
  vars: 
     Course: "Devops"
     trainer: "Shiva"
     duration: "110hrs"

  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, {{Course}}"