# 
- name: variables from file level
  hosts: localhost
  vars_files:
  - variables.yaml     
  tasks:
  - name: check variables
    ansible.builtin.debus:
      msg: "Hi {{course}}, i am {{trainer}} with {{duration}}"
     