- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
       name: "{{item}}"
       state: present
    loops:
    - git
    - mysql
    - postfix